# Generated by Django 2.2.14 on 2020-07-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200720_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='dfgsdfgs',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='jhgjgjhg',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='jhkjhkjhk',
        ),
    ]
